# Business Problem - Predict the Price of Bangalore House
#Using Linear Regression - Supervised Machine Learning Algorithm
 
### Load Libraries

### Load Data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\india\Desktop\Projects\ML Projects\Bengaluru_House_Data\PP bangalore house price prediction.csv")
df.head(100)

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0    3.0      2.0  150.0          1672.0    3     8971.291866   
1    3.0      3.0  149.0          1750.0    3     8514.285714   
2    3.0      2.0  150.0          1750.0    3     8571.428571   
3    2.0      2.0   40.0          1250.0    2     3200.000000   
4    2.0      2.0   83.0          1200.0    2     6916.666667   
..   ...      ...    ...             ...  ...             ...   
95   3.0      3.0  220.0          2100.0    3    10476.190476   
96   3.0      2.0  185.0          2400.0    3     7708.333333   
97   2.0      2.0   56.0          1206.0    2     4643.449420   
98   2.0      2.0   70.0          1270.0    3     5511.811024   
99   2.0      3.0   69.0          1312.0    2     5259.146341   

    area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                               1                        0   
1                               0                        1   
2                               1                        0   
3                               1                        0   
4                               0                        0   
..                            ...                      ...   
95                              1                        0   
96                              1                        0   
97                              1                        0   
98                              1                        0   
99                              1                        0   

    area_typePlot  Area  availability_Ready To Move  ...  \
0                     0                           1  ...   
1                     0                           1  ...   
2                     0                           1  ...   
3                     0                           1  ...   
4                     1                           1  ...   
..                  ...                         ...  ...   
95                    0                           1  ...   
96                    0                           1  ...   
97                    0                           1  ...   
98                    0                           1  ...   
99                    0                           1  ...   

    location_Kalena Agrahara  location_Horamavu Agara  \
0                          0                        0   
1                          0                        0   
2                          0                        0   
3                          0                        0   
4                          0                        0   
..                       ...                      ...   
95                         0                        0   
96                         0                        0   
97                         0                        0   
98                         0                        0   
99                         0                        0   

    location_Vidyaranyapura  location_BTM 2nd Stage  \
0                         0                       0   
1                         0                       0   
2                         0                       0   
3                         0                       0   
4                         0                       0   
..                      ...                     ...   
95                        0                       0   
96                        0                       0   
97                        0                       0   
98                        0                       0   
99                        0                       0   

    location_Hebbal Kempapura  location_Hosur Road  \
0                           0                    0   
1                           0                    0   
2                           0                    0   
3                           0                    0   
4                           0                    0   
..                        ...                  ...   
95                          0    

## Split Data

In [6]:
X = df.drop('price', axis=1)
y = df['price']

print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (7120, 107)
Shape of y =  (7120,)


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


## Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

## Support Vector Regression - ML Model Training

In [10]:
from sklearn.svm import SVR

In [11]:
svr_rbf = SVR(kernel='rbf')
svr_rbf.fit(X_train, y_train)
svr_rbf.score(X_test, y_test)

0.20638035840828173

In [12]:
svr_linear = SVR(kernel='linear')
svr_linear.fit(X_train, y_train)
svr_linear.score(X_test, y_test)

0.7962738959529407

In [13]:
svr_poly = SVR(kernel='poly',degree=2,)
svr_poly.fit(X_train, y_train)
svr_poly.score(X_test, y_test)

0.18266215211874626

## Predict the value of Home and Test

In [14]:
X_test[0]

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06

In [15]:
svr_linear.predict([X_test[0]])

array([86.53654472])

In [16]:
y_pred = svr_linear.predict(X_test)
y_pred

array([ 86.53654472,  33.70377084, 122.4841664 , ...,  26.23987068,
        64.52605129, 176.17641621])

In [17]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [18]:
from sklearn.metrics import mean_squared_error
import numpy as np

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print('MSE = ', mse)
print('RMSE = ', rmse)

MSE =  4093.4557563555695
RMSE =  63.980120008918156
